routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/','home');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('disaster','DisasterController');
Route::resource('user','UserController');
Route::get('user/profile/{id}','UserController@profile')->name('user.profile');
Route::get('user/profile/{id}/update','UserController@edit_profile')->name('user.profile.update');

Route::get('map/{id}','HomeController@view_disaster')->name('view_disaster');
Route::get('map/prev/{id}','HomeController@prev_disaster')->name('view_prev_disaster');
Route::get('map/next/{id}','HomeController@next_disaster')->name('view_next_disaster');
Route::get('disaster/views/all','DisasterController@view_all_disaster')->name('view_all_disaster');

Route::get('demo','DisasterController@demo');
Route::get('search/disaster/','DisasterController@search')->name('search_all_disaster');
Route::get('search/user/','UserController@search')->name('search_all_users');

app/Models/Disaster.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Disaster extends Model
{
    
    protected $fillable = [
        'type', 'loc', 'lat', 'lng'
    ];
}

app/Http/Controllers/DisasterController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Disaster;
use PulkitJalan\GeoIP\GeoIP;

class DisasterController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('disaster.index')->with(['disasters' => Disaster::paginate(20) ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('disaster.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'type' => 'required',
            'location' => 'required',
            'longtitude' => 'required',
            'latitude' => 'required',
        ]);
        Disaster::create([
            'type' => $request->type,
            'loc' => $request->location,
            'lng' => $request->longtitude,
            'lat' => $request->latitude
        ]);
        return redirect()->back()->with([
            'success' => 'Disaster added!'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('disaster.view')->with(['disaster' => Disaster::find($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('disaster.edit')->with(['disaster' => Disaster::find($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'type' => 'required',
            'location' => 'required',
            'longtitude' => 'required',
            'latitude' => 'required',
        ]);
        $disaster = Disaster::find($id);
        $disaster->type = $request->type; 
        $disaster->loc = $request->location;
        $disaster->lng = $request->longtitude; 
        $disaster->lat = $request->latitude;
        $disaster->save();
        return redirect()->back()->with([
            'success' => 'Disaster updated!'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $disaster = Disaster::find($id)->delete();
        return redirect()->route('disaster.index')->with([
            'success' => 'Record removed!'
        ]);
    }

    public function view_all_disaster()
    {
        // dd(\Request::getClientIp());
        // $geoip = new GeoIP();
        // dd($geoip->getLatitude());
        // dd(GeoIP::getLocation('27.974.399.6'));
        $disasters = Disaster::all();
        // dd($disasters);
        return view('disaster.all')->with([
            'disasters' => $disasters,
        ]);
    }

    public function demo()
    {
        return view('demo');
    }

    public function search(Request $request) 
    {
        // $disasters = Disaster::where('loc','like','%'.$request->search.'%')->orWhere('type','like','%'.$request->search.'%')->paginate(5);
        $disasters = Disaster::where('loc','like','%'.$request->search.'%')->paginate(5);
        return view('disaster.index')->with(['disasters' => $disasters ]);
    }
}

resources/views/disaster/create.blade.php
@extends('layouts.app')
@section('title','Add Disaster')
@section('content')
<div class="justify-center">
    <div class="w-1/4 md:mx-auto">
        <div class="text-center">
            <span class="text-grey-dark  text-lg">Add Disaster</span>
        </div>
        <div class="bg-white shadow-lg rounded flex flex-col my-2">
            <div class="px-8 pt-6 pb-8 mb-4 "> 
                <form method="POST" action="{{ route('disaster.store') }}">
                    @include('shared.alerts')
                    {{csrf_field()}}
                <div class="-mx-3 mb-0 ">
                    <div class="px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="type">
                            Type
                        </label>

                         <!--<input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3" id="type" type="text" name="type" value="{{ old('type') }}" placeholder="Earthquake">-->

                        <select class="appearance-none block w-full bg-grey-lighter text-grey-darker rounded py-3 px-4 mb-3" name="type" id="type" >
                            <option value="1" @if(old('type') == '1') selected @endif)>Earthquake</option>
                            <option value="2" @if(old('type') == '2') selected @endif>Floods</option>
                            <option value="3" @if(old('type') == '3') selected @endif>Landslide</option>
                            <option value="4" @if(old('type') == '4') selected @endif>Evacuation Center</option>    
                        </select>

                        {{-- <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3" id="type" type="text" name="type" value="{{ old('type') }}" placeholder="Earthquake"> --}}
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="location">
                                Location
                            </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-grey-lighter rounded py-3 px-4 mb-3" id="location" value="{{ old('location') }}" name="location" type="text" placeholder="Goa, Camarines Sur">
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="longtitude">
                                Longitude
                            </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3" id="longtitude" type="longtitude" value="{{ old('longtitude') }}" name="longtitude">
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                    <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="latitude">
                                Latitude
                            </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-grey-lighter rounded py-3 px-4 mb-3" id="latitude" value="{{ old('latitude') }}" name="latitude" type="text">
                    </div>
                </div>
                <div class="-mx-3 md:flex">
                    <div class="md:w-4/5 px-3 mb-0 md:mb-0">
                        <button class="bg-blue hover:bg-blue-light text-white font-bold py-2 px-4 border-b-4 border-blue-dark hover:border-blue rounded">
                            Save
                        </button>
                    </div>
                    <div class="md:w-auto px-3">
                        <a href="{{ route('disaster.index') }}"class="inline-flex bg-red hover:bg-red-light text-white font-bold py-2 px-4 border-b-4 border-red-dark hover:border-blue rounded">
                            Back
                        </a>
                    </div>
                </div>
            </div>
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/disaster/edit.blade.php
@extends('layouts.app')
@section('title','Update Disaster')
@section('content')
<div class="justify-center">
    <div class="w-1/4 md:mx-auto">
        <div class="text-center">
            <span class="text-grey-dark  text-lg">Update Disaster</span>
        </div>
        <div class="bg-white shadow-lg rounded flex flex-col my-2">
            <div class="px-8 pt-6 pb-8 mb-4 "> 
                <form method="POST" action="{{ route('disaster.update',$disaster->id) }}">
                    @include('shared.alerts')
                    {{csrf_field()}}
                    {{ method_field('PATCH') }} 
                <div class="-mx-3 mb-0 ">
                    <div class="px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="type">
                            type
                        </label>
                        
                             <!--<input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3" id="type" type="text" name="type" value="{{ $disaster->type }}" placeholder="Earthquake">-->

                        <select class="appearance-none block w-full bg-grey-lighter text-grey-darker rounded py-3 px-4 mb-3" name="type" id="type" >
                            <option value="1" @if($disaster->type == '1') selected @endif)>Earthquake</option>
                            <option value="2" @if($disaster->type == '2') selected @endif>Floods</option>
                            <option value="3" @if($disaster->type == '3') selected @endif>Landslide</option>
                            <option value="4" @if($disaster->type == '4') selected @endif>Evacuation Center</option>    
                        </select>
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="location">
                                Location
                            </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-grey-lighter rounded py-3 px-4 mb-3" id="location" value="{{ $disaster->loc }}" name="location" type="text" placeholder="Bacoor, Cavite">
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="longtitude">
                                Longtitude
                            </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3" id="longtitude" type="longtitude" value="{{ $disaster->lng }}" name="longtitude">
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                    <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="latitude">
                                Latitude
                            </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-grey-lighter rounded py-3 px-4 mb-3" id="latitude" value="{{ $disaster->lat }}" name="latitude">
                    </div>
                </div>
                <div class="-mx-3 md:flex">
                    <div class="md:w-4/5 px-3 mb-0 md:mb-0">
                        <button class="bg-blue hover:bg-blue-light text-white font-bold py-2 px-4 border-b-4 border-blue-dark hover:border-blue rounded">
                            Update
                        </button>
                    </div>
                    <div class="md:w-auto px-3">
                        <a href="{{ route('disaster.index') }}"class="inline-flex bg-red hover:bg-red-light text-white font-bold py-2 px-4 border-b-4 border-red-dark hover:border-blue rounded">
                            Back
                        </a>
                    </div>
                </div>
            </div>
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/disaster/index.blade.php
@extends('layouts.app')
@section('title','List All Disaster')
@section('content')
<div class="justify-center">

    <div class="w-4/5 md:mx-auto">
        
        <div class="rounded-none shadow-lg bg-white border-2">
            @if (session('success'))
            <div class="flex bg-green-lighter w-auto">
                    <div class="w-16 bg-green">
                        <div class="p-4">
                            <svg class="h-8 w-8 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M468.907 214.604c-11.423 0-20.682 9.26-20.682 20.682v20.831c-.031 54.338-21.221 105.412-59.666 143.812-38.417 38.372-89.467 59.5-143.761 59.5h-.12C132.506 459.365 41.3 368.056 41.364 255.883c.031-54.337 21.221-105.411 59.667-143.813 38.417-38.372 89.468-59.5 143.761-59.5h.12c28.672.016 56.49 5.942 82.68 17.611 10.436 4.65 22.659-.041 27.309-10.474 4.648-10.433-.04-22.659-10.474-27.309-31.516-14.043-64.989-21.173-99.492-21.192h-.144c-65.329 0-126.767 25.428-172.993 71.6C25.536 129.014.038 190.473 0 255.861c-.037 65.386 25.389 126.874 71.599 173.136 46.21 46.262 107.668 71.76 173.055 71.798h.144c65.329 0 126.767-25.427 172.993-71.6 46.262-46.209 71.76-107.668 71.798-173.066v-20.842c0-11.423-9.259-20.683-20.682-20.683z"/><path d="M505.942 39.803c-8.077-8.076-21.172-8.076-29.249 0L244.794 271.701l-52.609-52.609c-8.076-8.077-21.172-8.077-29.248 0-8.077 8.077-8.077 21.172 0 29.249l67.234 67.234a20.616 20.616 0 0 0 14.625 6.058 20.618 20.618 0 0 0 14.625-6.058L505.942 69.052c8.077-8.077 8.077-21.172 0-29.249z"/></svg>
                        </div>
                    </div>
                    <div class="w-auto text-grey-darker items-center p-4">
                        <span class="text-lg font-bold pb-4">
                            Heads Up!
                        </span>
                        <p class="leading-tight">
                            {{ session('success') }}
                        </p>
                    </div>
                </div>
            @endif
            <div class="flex bg-grey-lighter">
                <div class="w-full sm:w-full md:w-full xl:w-3/5 lg:w-3/5 p-2">
                    <form action="{{ route('search_all_disaster', ['search' => isset($search) ]) }}" method="GET">
                        <input type="search" class="bg-purple-white shadow rounded border-0 p-3 w-100" placeholder="Search..." name="search">
                        <button class="bg-blue hover:bg-blue-dark text-white font-bold py-3 px-8 rounded">
                            Search
                        </button>
                    </form>
                </div>
                <div class="w-full sm:w-full md:w-full xl:w-2/5 lg:w-2/5 p-2 ">
                    <div class="flex flex-wrap justify-end">
                        <div class="w-auto mr-6">
                            @if(Auth::user()->id == 1)
                            <a class="bg-blue hover:bg-blue-dark text-white font-bold py-3 px-8 rounded" style="display:inline-block;" href="{{ route('disaster.create') }}">
                                Add Disaster
                            </a>
                             @endif
                        </div>
                        <div class="w-auto">
                            <a class="bg-blue hover:bg-blue-dark text-white font-bold py-3 px-8 rounded" style="display:inline-block;" href="{{ route('view_all_disaster') }}">
                                View Disaster(s)
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <table class="border-bottom w-full">
                <thead class="text-red border-solid border-8">
                    <th>ID</th>
                    <th>Type</th>
                    <th>Location</th>
                    <th>Longtitude</th>
                    <th>Latitude</th>
                    <th>Map</th>
                </thead>
                <tbody>
                    @foreach($disasters as $disaster)
                    <tr @if($disaster->id % 2) class="bg-blue-lightest" @endif>
                        <td class="text-center">{{ $disaster->id }}</td>

                        <!--<td class="text-center">{{ $disaster->type }}</td>-->

                        <td class="text-center">
                            @if($disaster->type == '1')
                                Earthquake
                            @elseif($disaster->type == '2')
                                Floods
                            @elseif($disaster->type == '3')
                                Landslides
                            @elseif($disaster->type == '4')
                                Evacuation Areas    
                            @endif
                        </td>
                        <td class="text-center"><a href="{{ route('disaster.show',['id' => $disaster->id]) }}" class="text-blue hover:text-blue-darker">{{ $disaster->loc }}</a></td>
                        <td class="text-center">{{ $disaster->lng }}</td>
                        <td class="text-center">{{ $disaster->lat }}</td>
                        <td class="text-center"><a href="{{ route('view_disaster',$disaster->id) }}" class="text-grey-darkest " target="_blank">
                            <svg class="fill-current text-teal inline-block h-6 w-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                <path d="M10 20a10 10 0 1 1 0-20 10 10 0 0 1 0 20zm2-2.25a8 8 0 0 0 4-2.46V9a2 2 0 0 1-2-2V3.07a7.95 7.95 0 0 0-3-1V3a2 2 0 0 1-2 2v1a2 2 0 0 1-2 2v2h3a2 2 0 0 1 2 2v5.75zm-4 0V15a2 2 0 0 1-2-2v-1h-.5A1.5 1.5 0 0 1 4 10.5V8H2.25A8.01 8.01 0 0 0 8 17.75z"/>
                            </svg>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $disasters->links('vendor.pagination.default') }}
        </div>
    </div>
</div>
@endsection

resources/views/disaster/view.blade.php
@extends('layouts.app')
@section('title','List All Disaster')
@section('content')
<div class="justify-center">
    <div class="w-1/4 md:mx-auto">
        <div class="text-center">
            <span class="text-grey-dark  text-lg">View Disaster</span>
        </div>
        <div class="bg-white shadow-lg rounded flex flex-col my-2">
            <div class="px-8 pt-6 pb-8 mb-4 "> 
                <div class="-mx-3 mb-0 ">
                    <div class="px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="type">
                            type
                        </label>

                            <!--<input class="appearance-none block w-full bg-grey-lighter text-grey-darker cursor-not-allowed rounded py-3 px-4 mb-3" disabled id="type" type="text" name="type" value="{{ $disaster->type }}">-->

                        <select class="appearance-none block w-full bg-grey-lighter text-grey-darker rounded py-3 px-4 mb-3" name="type" id="type" disabled >
                            <option value="1" @if($disaster->type == '1') selected @endif)>Earthquake</option>
                            <option value="2" @if($disaster->type == '2') selected @endif>Floods</option>
                            <option value="3" @if($disaster->type == '3') selected @endif>Landslide</option>
                            <option value="4" @if($disaster->type == '4') selected @endif>Evacuation Center</option>    
                        </select>                    
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="location">
                                Location
                            </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker cursor-not-allowed border border-grey-lighter rounded py-3 px-4 mb-3" disabled id="location" value="{{  $disaster->loc }}" name="location" type="text">
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="longtitude">
                                Longtitude
                            </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  cursor-not-allowed rounded py-3 px-4 mb-3" id="longtitude" disabled type="longtitude" value="{{  $disaster->lng }}" name="longtitude">
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                    <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="latitude">
                                Latitude
                            </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker border cursor-not-allowed border-grey-lighter rounded py-3 px-4 mb-3" disabled id="latitude" value="{{  $disaster->lat }}" name="latitude" type="text">
                    </div>
                </div>
                <div class="-mx-3 md:flex">

                    @if(Auth::user()->id == 1)
                    <div class="md:w-4/5 px-3 mb-0 md:mb-0">
                        <a href="{{ route('disaster.edit',$disaster->id) }}"class="inline-flex bg-green hover:bg-green-light text-white font-bold py-2 px-4 border-b-4 border-green-dark hover:border-blue rounded">
                            Update
                        </a>
                    </div>
                    <div class="md:w-4/5 px-3 mb-0 md:mb-0">
                        <a href="{{ route('disaster.destroy',$disaster->id) }}"class="inline-flex bg-red hover:bg-red-light text-white font-bold py-2 px-4 border-b-4 border-red-dark hover:border-red rounded" 
                            onclick="event.preventDefault();
                                document.getElementById('destroy-form-{{ $disaster->id}}').submit();">
                            Delete
                        </a>
                        <form id="destroy-form-{{ $disaster->id }}" action="{{ route('disaster.destroy',$disaster->id) }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                                {{ method_field('DELETE')}}
                        </form>
                    </div>
                    @endif

                    <div class="md:w-auto px-3">
                        <a href="{{ route('disaster.index') }}"class="inline-flex bg-blue hover:bg-blue-light text-white font-bold py-2 px-4 border-b-4 border-blue-dark hover:border-blue rounded">
                            Back
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection