routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/','home');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('disaster','DisasterController');
Route::resource('user','UserController');
Route::get('user/profile/{id}','UserController@profile')->name('user.profile');
Route::get('user/profile/{id}/update','UserController@edit_profile')->name('user.profile.update');

Route::get('map/{id}','HomeController@view_disaster')->name('view_disaster');
Route::get('map/prev/{id}','HomeController@prev_disaster')->name('view_prev_disaster');
Route::get('map/next/{id}','HomeController@next_disaster')->name('view_next_disaster');
Route::get('disaster/views/all','DisasterController@view_all_disaster')->name('view_all_disaster');

Route::get('demo','DisasterController@demo');
Route::get('search/disaster/','DisasterController@search')->name('search_all_disaster');
Route::get('search/user/','UserController@search')->name('search_all_users');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'firstname','middlename','lastname', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute ($value) {
        $this->attributes['password'] = bcrypt($value);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Auth;
class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function get_user()
    {
        $user = Auth::user()->id;
        // dd($user);
        return $user    == '1' ? true : false;
    }

    public function is_user_valid($view)
    {
        return $this->get_user() ? $view : error(404);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $view = view('user.index')->with([ 'users' => User::where('id','!=',Auth::user()->id)->paginate(30) ]);
        return $this->is_user_valid($view);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'firstname' => 'required',  
            'middlename' => 'required',
            'lastname' => 'required',
            'email' => 'required|unique:users,email',
            'password' => 'required|min:6|confirmed'
        ]);
        User::create([
            'firstname' => $request->firstname,
            'middlename' => $request->middlename,
            'lastname' => $request->lastname,
            'email' => $request->email,
            'password' => $request->password
        ]);
        return redirect()->back()->with([
            'success' => 'User created!'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('user.show')->with([ 'user' => User::find($id )]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('user.edit')->with([ 'user' => User::find($id) ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $test = $this->validate($request,[
            'firstname' => 'required',
            'lastname' => 'required',
            'middlename' => 'required',
            'email' => 'required|email|unique:users,email,'.$id,
            'password' => 'nullable|min:6'
        ]);
        $user = User::find($id);
        $user->firstname = $request->firstname;
        $user->middlename = $request->middlename;
        $user->lastname = $request->lastname;
        $user->email = $request->email;
        if ($request->password) {
           $user->password = $request->password; 
        }
        $user->save();
        return redirect()->back()->with([
            'success' => 'User updated!'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $disaster = User::find($id)->delete();
        return redirect()->route('user.index')->with([
            'success' => 'Record removed!'
        ]);
    }
    
    public function profile($id)
    {
        return view('user.profile')->with([ 'user' => User::find($id) ]);
    }
    public function edit_profile($id)
    {
        return view('user.update')->with([ 'user' => User::find($id) ]);

    }

    public function search(Request $request) 
    {
        // $disasters = Disaster::where('loc','like','%'.$request->search.'%')->orWhere('type','like','%'.$request->search.'%')->paginate(5);

        $users = User::where('firstname','like','%'.$request->search.'%')->paginate(5);

        //$users = User::where('firstname','like','%'.$request->search.'%')
                    //->orWhere('middlename','like','%'.$request->search.'%')
                    //->orWhere('lastname','like','%'.$request->search.'%')
                    //->orWhere('email','like','%'.$request->search.'%')
                    //->paginate(5);
                     //($users);
        //$view = view('user.index')->with([ 'users' => User::where('id','!=',Auth::user()->id)->paginate(30) ]);
        //return $this->is_user_valid($view);
         $view = view('user.index')->with([ 'users' => $users ]);
         return $this->is_user_valid($view);
    }

}

resources/views/user/create.blade.php
@extends('layouts.app')
@section('title','Edit User')
@section('content')
<div class="justify-center">
    <div class="w-1/4 md:mx-auto">
        <div class="text-center">
            <span class="text-grey-dark  text-lg">Create User</span>
        </div>
        <div class="bg-white shadow-lg rounded flex flex-col my-2">
            <form method="POST" action="{{ route('user.store') }}">
                {{ csrf_field() }} 
                @include('shared.alerts')
            <div class="px-8 pt-6 pb-8 mb-4 "> 
                <div class="-mx-3 mb-0 ">
                    <div class="px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="firstname">
                            Firstname
                        </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 "  id="firstname"  name="firstname" value="{{ old('firstname') }}">
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="middlename">
                                middlename
                            </label>
                            <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 "  id="middlename"  name="middlename" value="{{ old('middlename') }}">
                        </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="lastname">
                                lastname
                            </label>
                            <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3"  id="lastname"  name="lastname" value="{{ old('lastname') }}">
                        </div>
                </div>
                <div class="-mx-3 mb-0 ">
                    <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="email">
                                Email
                            </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 "  id="email"  name="email" value="{{ old('email') }}">
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                    <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="password">
                                Password
                            </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 "  type="password" id="password"  name="password">
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                            <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="password_confirmation">
                                    Confirm Password
                                </label>
                            <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 " type="password" id="password_confirmation"  name="password_confirmation">
                        </div>
                    </div>
                <div class="-mx-3 md:flex">
                    <div class="md:w-4/5 px-3 mb-0 md:mb-0">
                        <button href="{{ route('user.store') }}"class="inline-flex bg-green hover:bg-green-light text-white font-bold py-2 px-4 border-b-4 border-green-dark hover:border-blue rounded">
                            Create
                        </button>
                    </form>

                    </div>
                
                    <div class="md:w-auto px-3">
                        <a href="{{ route('user.index') }}"class="inline-flex bg-blue hover:bg-blue-light text-white font-bold py-2 px-4 border-b-4 border-blue-dark hover:border-blue rounded">
                            Back
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')
@section('title','Edit User')
@section('content')
<div class="justify-center">
    <div class="w-1/4 md:mx-auto">
        <div class="text-center">
            <span class="text-grey-dark  text-lg">Update User</span>
        </div>
        <div class="bg-white shadow-lg rounded flex flex-col my-2">
            <form method="POST" action="{{ route('user.update',$user->id) }}">
                {{ csrf_field() }} {{ method_field('PATCH') }}
                @include('shared.alerts')
            <div class="px-8 pt-6 pb-8 mb-4 "> 
                <div class="-mx-3 mb-0 ">
                    <div class="px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="firstname">
                            Firstname
                        </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 "  id="firstname"  name="firstname" value="{{ $user->firstname }}">
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="middlename">
                                middlename
                            </label>
                            <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 "  id="middlename"  name="middlename" value="{{ $user->middlename }}">
                        </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="lastname">
                                lastname
                            </label>
                            <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3"  id="lastname"  name="lastname" value="{{ $user->lastname }}">
                        </div>
                </div>
                <div class="-mx-3 mb-0 ">
                    <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="email">
                                Email
                            </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 "  id="email"  name="email" value="{{ $user->email }}">
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                    <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="password">
                                Password
                            </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 "  id="password"  name="password">
                    </div>
                </div>
                <div class="-mx-3 md:flex">
                    <div class="md:w-4/5 px-3 mb-0 md:mb-0">
                        <button href="{{ route('user.edit',$user->id) }}"class="inline-flex bg-green hover:bg-green-light text-white font-bold py-2 px-4 border-b-4 border-green-dark hover:border-blue rounded">
                            Update
                        </button>
                    </form>

                    </div>
                
                    <div class="md:w-auto px-3">
                        <a href="{{ route('user.index') }}"class="inline-flex bg-blue hover:bg-blue-light text-white font-bold py-2 px-4 border-b-4 border-blue-dark hover:border-blue rounded">
                            Back
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')
@section('title','List All User')
@section('content')
<div class="justify-center">

    <div class="w-4/5 md:mx-auto">
        
        <div class="rounded-none shadow-lg bg-white border-2">
            @if (session('success'))
            <div class="flex bg-green-lighter w-auto">
                    <div class="w-16 bg-green">
                        <div class="p-4">
                            <svg class="h-8 w-8 text-white fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M468.907 214.604c-11.423 0-20.682 9.26-20.682 20.682v20.831c-.031 54.338-21.221 105.412-59.666 143.812-38.417 38.372-89.467 59.5-143.761 59.5h-.12C132.506 459.365 41.3 368.056 41.364 255.883c.031-54.337 21.221-105.411 59.667-143.813 38.417-38.372 89.468-59.5 143.761-59.5h.12c28.672.016 56.49 5.942 82.68 17.611 10.436 4.65 22.659-.041 27.309-10.474 4.648-10.433-.04-22.659-10.474-27.309-31.516-14.043-64.989-21.173-99.492-21.192h-.144c-65.329 0-126.767 25.428-172.993 71.6C25.536 129.014.038 190.473 0 255.861c-.037 65.386 25.389 126.874 71.599 173.136 46.21 46.262 107.668 71.76 173.055 71.798h.144c65.329 0 126.767-25.427 172.993-71.6 46.262-46.209 71.76-107.668 71.798-173.066v-20.842c0-11.423-9.259-20.683-20.682-20.683z"/><path d="M505.942 39.803c-8.077-8.076-21.172-8.076-29.249 0L244.794 271.701l-52.609-52.609c-8.076-8.077-21.172-8.077-29.248 0-8.077 8.077-8.077 21.172 0 29.249l67.234 67.234a20.616 20.616 0 0 0 14.625 6.058 20.618 20.618 0 0 0 14.625-6.058L505.942 69.052c8.077-8.077 8.077-21.172 0-29.249z"/></svg>
                        </div>
                    </div>
                    <div class="w-auto text-grey-darker items-center p-4">
                        <span class="text-lg font-bold pb-4">
                            Heads Up!
                        </span>
                        <p class="leading-tight">
                            {{ session('success') }}
                        </p>
                    </div>
                </div>
            @endif
            <div class="flex bg-grey-lighter">
                
                   <!--action="{{ route('search_all_disaster', ['search' => isset($search) ]) }}" method="GET">-->

                <div class="w-full p-2" >
                    <form action="{{ route('search_all_users', ['search' => isset($search) ]) }}" method="GET">
                        <input type="search" class="bg-purple-white shadow rounded border-0 p-3 w-100" placeholder="Search by name" name="search">
                        <button class="bg-blue hover:bg-blue-dark text-white font-bold py-3 px-8 rounded">
                            Search
                        </button>
                    </form>
                </div>
                <div class="w-1/6  p-2" >
                    <a class=" bg-blue hover:bg-blue-dark text-white font-bold py-3 px-8 rounded" style="display:inline-block;" href="{{ route('user.create') }}">
                        Add User
                    </a>
                </div>
            </div>

            <table  class="border-bottom w-full";>
                <thead class="text-red border-solid border-8">
                    <th>ID</th>
                    <th>Firstname</th>
                    <th>Middlename</th>
                    <th>Lastname</th>
                    <th>Email</th>
                </thead>
                <tbody>
                    @foreach($users as $user)
                    <tr @if($user->id % 2) class="bg-blue-lightest" @endif>
                        <td class="text-center">{{ $user->id }}</td>
                        <td class="text-center"><a href="{{ route('user.show',$user->id) }}"  class="text-blue hover:text-blue-darker">{{ $user->firstname }}</a></td>
                        <td class="text-center">{{ $user->middlename }}</td>
                        <td class="text-center">{{ $user->lastname }}</td>
                        <td class="text-center">{{ $user->email }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $users->links('vendor.pagination.default') }}
        </div>
    </div>
</div>
@endsection

resources/views/user/profile.blade.php
@extends('layouts.app')
@section('title','Create User')
@section('content')
<div class="justify-center">
    <div class="w-1/4 md:mx-auto">
        <div class="text-center">
            <span class="text-grey-dark  text-lg">View User</span>
        </div>
        <div class="bg-white shadow-lg rounded flex flex-col my-2">
            <div class="px-8 pt-6 pb-8 mb-4 "> 
                <div class="-mx-3 mb-0 ">
                    <div class="px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="firstname">
                            Firstname
                        </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 cursor-not-allowed" disabled id="firstname"  name="firstname" value="{{ $user->firstname }}">
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="middlename">
                                Middlename
                            </label>
                            <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 cursor-not-allowed" disabled id="middlename"  name="middlename" value="{{ $user->middlename }}">
                        </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="lastname">
                                Lastname
                            </label>
                            <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 cursor-not-allowed" disabled id="lastname"  name="lastname" value="{{ $user->lastname }}">
                        </div>
                </div>
                <div class="-mx-3 mb-0 ">
                    <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="email">
                                Email
                            </label>
                            <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 cursor-not-allowed" disabled id="email"  name="email" value="{{ $user->email }}">
                        </div>
                </div>
                <div class="-mx-3 md:flex">
                    @if(Auth::user()->id == 1)
                    <div class="md:w-4/5 px-3 mb-0 md:mb-0">
                        <a href="{{ route('user.profile.update',$user->id) }}"class="inline-flex bg-green hover:bg-green-light text-white font-bold py-2 px-4 border-b-4 border-green-dark hover:border-blue rounded">
                            Update
                        </a>
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')
@section('title','Create User')
@section('content')
<div class="justify-center">
    <div class="w-1/4 md:mx-auto">
        <div class="text-center">
            <span class="text-grey-dark  text-lg">View User</span>
        </div>
        <div class="bg-white shadow-lg rounded flex flex-col my-2">
            <div class="px-8 pt-6 pb-8 mb-4 "> 
                <div class="-mx-3 mb-0 ">
                    <div class="px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="firstname">
                            Firstname
                        </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 cursor-not-allowed" disabled id="firstname"  name="firstname" value="{{ $user->firstname }}">
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="middlename">
                                Middlename
                            </label>
                            <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 cursor-not-allowed" disabled id="middlename"  name="middlename" value="{{ $user->middlename }}">
                        </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="lastname">
                                Lastname
                            </label>
                            <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 cursor-not-allowed" disabled id="lastname"  name="lastname" value="{{ $user->lastname }}">
                        </div>
                </div>
                <div class="-mx-3 mb-0 ">
                    <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="email">
                                Email
                            </label>
                            <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 cursor-not-allowed" disabled id="email"  name="email" value="{{ $user->email }}">
                        </div>
                </div>
                <div class="-mx-3 md:flex">
                    <div class="md:w-4/5 px-3 mb-0 md:mb-0">
                        <a href="{{ route('user.edit',$user->id) }}"class="inline-flex bg-green hover:bg-green-light text-white font-bold py-2 px-4 border-b-4 border-green-dark hover:border-blue rounded">
                            Update
                        </a>
                    </div>
                    <div class="md:w-4/5 px-3 mb-0 md:mb-0">
                        <a href="{{ route('user.destroy',$user->id) }}"class="inline-flex bg-red hover:bg-red-light text-white font-bold py-2 px-4 border-b-4 border-red-dark hover:border-red rounded" 
                            onclick="event.preventDefault();
                                document.getElementById('destroy-form').submit();">
                            Delete
                        </a>
                        <form id="destroy-form" action="{{ route('user.destroy',$user->id) }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                                {{ method_field('DELETE')}}
                        </form>
                    </div>
                    <div class="md:w-auto px-3">
                        <a href="{{ route('user.index') }}"class="inline-flex bg-blue hover:bg-blue-light text-white font-bold py-2 px-4 border-b-4 border-blue-dark hover:border-blue rounded">
                            Back
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/update.blade.php
@extends('layouts.app')
@section('title','Edit User')
@section('content')
<div class="justify-center">
    <div class="w-1/4 md:mx-auto">
        <div class="text-center">
            <span class="text-grey-dark  text-lg">Update User</span>
        </div>
        <div class="bg-white shadow-lg rounded flex flex-col my-2">
            <form method="POST" action="{{ route('user.update',$user->id) }}">
                {{ csrf_field() }} {{ method_field('PATCH') }}
                @include('shared.alerts')
            <div class="px-8 pt-6 pb-8 mb-4 "> 
                <div class="-mx-3 mb-0 ">
                    <div class="px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="firstname">
                            Firstname
                        </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 "  id="firstname"  name="firstname" value="{{ $user->firstname }}">
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="middlename">
                                middlename
                            </label>
                            <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 "  id="middlename"  name="middlename" value="{{ $user->middlename }}">
                        </div>
                </div>
                <div class="-mx-3 mb-0 ">
                        <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="lastname">
                                lastname
                            </label>
                            <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3"  id="lastname"  name="lastname" value="{{ $user->lastname }}">
                        </div>
                </div>
                <div class="-mx-3 mb-0 ">
                    <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="email">
                                Email
                            </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 "  id="email"  name="email" value="{{ $user->email }}">
                    </div>
                </div>
                <div class="-mx-3 mb-0 ">
                    <div class=" px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="password">
                                Password
                            </label>
                        <input class="appearance-none block w-full bg-grey-lighter text-grey-darker  rounded py-3 px-4 mb-3 "  type="password" id="password"  name="password">
                    </div>
                </div>
                <div class="-mx-3 md:flex">
                    <div class="md:w-4/5 px-3 mb-0 md:mb-0">
                        <button href="{{ route('user.edit',$user->id) }}"class="inline-flex bg-green hover:bg-green-light text-white font-bold py-2 px-4 border-b-4 border-green-dark hover:border-blue rounded">
                            Save
                        </button>
                    </form>

                    </div>
                
                    <div class="md:w-auto px-3">
                        <a href="{{ route('user.profile',$user->id) }}"class="inline-flex bg-blue hover:bg-blue-light text-white font-bold py-2 px-4 border-b-4 border-blue-dark hover:border-blue rounded">
                            Back
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection